config/routes.rb
Rails.application.routes.draw do
  resources :date_differences
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/date_difference.rb
class DateDifference < ApplicationRecord

    validates :date1, presence: true
    validates :date2, presence: true

    before_create :set_diff
    before_update :set_diff

    protected
    def set_diff
        self.diff = (Date.parse(self.date1) - Date.parse(self.date2)).to_i.abs
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/date_differences_controller.rb
class DateDifferencesController < ApplicationController
  before_action :set_date_difference, only: %i[ show edit update destroy ]

  # GET /date_differences or /date_differences.json
  def index
    @date_differences = DateDifference.all
  end

  # GET /date_differences/1 or /date_differences/1.json
  def show
  end

  # GET /date_differences/new
  def new
    @date_difference = DateDifference.new
  end

  # GET /date_differences/1/edit
  def edit
  end

  # POST /date_differences or /date_differences.json
  def create
    @date_difference = DateDifference.new(date_difference_params)

    respond_to do |format|
      if @date_difference.save
        format.html { redirect_to date_difference_url(@date_difference), notice: "Date difference was successfully created." }
        format.json { render :show, status: :created, location: @date_difference }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @date_difference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /date_differences/1 or /date_differences/1.json
  def update
    respond_to do |format|
      if @date_difference.update(date_difference_params)
        format.html { redirect_to date_difference_url(@date_difference), notice: "Date difference was successfully updated." }
        format.json { render :show, status: :ok, location: @date_difference }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @date_difference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /date_differences/1 or /date_differences/1.json
  def destroy
    @date_difference.destroy

    respond_to do |format|
      format.html { redirect_to date_differences_url, notice: "Date difference was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_date_difference
      @date_difference = DateDifference.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def date_difference_params
      params.require(:date_difference).permit(:date1, :date2)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/date_differences_helper.rb
module DateDifferencesHelper
end

app/views/date_differences/_date_difference.html.erb
<div id="<%= dom_id date_difference %>">
  <p>
    <strong>Date1:</strong>
    <%= date_difference.date1 %>
  </p>

  <p>
    <strong>Date2:</strong>
    <%= date_difference.date2 %>
  </p>

  <p>
    <strong>Diff:</strong>
    <%= date_difference.diff %>
  </p>

</div>

app/views/date_differences/_form.html.erb
<%= form_with(model: date_difference) do |form| %>
  <% if date_difference.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(date_difference.errors.count, "error") %> prohibited this date_difference from being saved:</h2>

      <ul>
        <% date_difference.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date1, style: "display: block" %>
    <%= form.text_field :date1 %>
  </div>

  <div>
    <%= form.label :date2, style: "display: block" %>
    <%= form.text_field :date2 %>
  </div>

  <div class='input-group date' id='datetimepicker1'>
    <input type='text' class="form-control" />
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
  </div>
  <div class='input-group date' id='datetimepicker2'>
    <input type='text' class="form-control" />
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
  </div>
  <script type="text/javascript">
    (function () {
      document.getElementById('datetimepicker1').datetimepicker();
      document.getElementById('datetimepicker2').datetimepicker();
    })();
  </script>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/date_differences/edit.html.erb
<h1>Editing date difference</h1>

<%= render "form", date_difference: @date_difference %>

<br>

<div>
  <%= link_to "Show this date difference", @date_difference %> |
  <%= link_to "Back to date differences", date_differences_path %>
</div>

app/views/date_differences/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Date differences</h1>

<div id="date_differences">
  <% @date_differences.each do |date_difference| %>
    <%= render date_difference %>
    <p>
      <%= link_to "Show this date difference", date_difference %>
    </p>
  <% end %>
</div>

<%= link_to "New date difference", new_date_difference_path %>

app/views/date_differences/new.html.erb
<h1>New date difference</h1>

<%= render "form", date_difference: @date_difference %>

<br>

<div>
  <%= link_to "Back to date differences", date_differences_path %>
</div>

app/views/date_differences/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @date_difference %>

<div>
  <%= link_to "Edit this date difference", edit_date_difference_path(@date_difference) %> |
  <%= link_to "Back to date differences", date_differences_path %>

  <%= button_to "Destroy this date difference", @date_difference, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DateDiff</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>